CREATE DATABASE IF NOT EXISTS test_db;
USE test_db;

CREATE TABLE IF NOT EXISTS systemuser (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  password VARCHAR(45) NOT NULL,
  userTypeId INT,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CreatedBy VARCHAR(45)
);